development:
  database: api_trial
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db
test:
  database: api_trial_test
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db